
/** COODINATE **/
//#define SPHERICAL_POLAR_COORD
#define CARTESIAN_COORD

/** PROTECTION **/
//#define PROTECTION_PROTECTION

/** GRAVITY **/
//#define ENABLE_GRAVITY

/** DUST **/
//#define ENABLE_DUSTFLUID
// #define DUST_PROTECTION

/** DEBUG **/
// #define DEBUG
