
/** COODINATE **/
#define SPHERICAL_POLAR_COORD
//#define CARTESIAN_COORD

/** PROTECTION **/
//#define DENSITY_PROTECTION
#define ENABLE_TEMPERATURE_PROTECTION

/** GRAVITY **/
#define ENABLE_GRAVITY

/** DUST **/
// #define ENABLE_DUSTFLUID
// #define DUST_PROTECTION

/** DEBUG **/
#define DEBUG
