
/** COODINATE **/
#define CARTESIAN_COORD
//#define SPHERICAL_POLAR_COORD

/** PROTECTION **/
#define DENSITY_PROTECTION
#define ENABLE_TEMPERATURE_PROTECTION

/** GRAVITY **/
#define ENABLE_GRAVITY

/** DUST **/
#define ENABLE_DUSTFLUID
#define ENABLE_DUST_GRAINGROWTH

/** DEBUG **/
//#define DEBUG

/** VISCOSITY **/
//#define ENABLE_VISCOSITY
